import { Navbar } from "@/components/navbar/Navbar";
import { type NextPage } from "next";
import { signIn } from "next-auth/react";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex min-h-screen w-full flex-col items-center pt-16">
        <section className="mt-8 text-center">
          <h1 className="text-5xl font-bold sm:text-6xl">Score Manager</h1>
          <p className="py-2 text-lg italic text-gray-500">
            Some description here...
          </p>
          <div className="flex justify-center gap-4 py-8">
            <button
              className="rounded-lg bg-gray-300 px-4 py-2"
              onClick={() => void signIn("nycu")}
            >
              Login with NYCU OAuth
            </button>
            <button
              className="rounded-lg bg-gray-300 px-4 py-2"
              onClick={() => void signIn("nycu")}
            >
              Login with NYCU OAuth
            </button>
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;
